vim.cmd [[hi clear]]
vim.cmd [[syntax reset]]
vim.cmd [[let g:colors_name = "green_pink_theme"]]
vim.cmd [[set background=dark]]
vim.cmd [[set t_Co=256]]
vim.cmd [[hi Normal guifg=#dadada ctermbg=NONE guibg=#213531 gui=NONE]]

vim.cmd [[hi DiffText guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi ErrorMsg guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi WarningMsg guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi PreProc guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi Exception guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi Error guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi DiffDelete guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi GitGutterDelete guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi GitGutterChangeDelete guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi cssIdentifier guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi cssImportant guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi Type guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi Identifier guifg=#ff4190 guibg=NONE]]
vim.cmd [[hi PMenuSel guifg=#13f860 guibg=NONE]]
vim.cmd [[hi Constant guifg=#13f860 guibg=NONE]]
vim.cmd [[hi Repeat guifg=#13f860 guibg=NONE]]
vim.cmd [[hi DiffAdd guifg=#13f860 guibg=NONE]]
vim.cmd [[hi GitGutterAdd guifg=#13f860 guibg=NONE]]
vim.cmd [[hi cssIncludeKeyword guifg=#13f860 guibg=NONE]]
vim.cmd [[hi Keyword guifg=#13f860 guibg=NONE]]
vim.cmd [[hi IncSearch guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Title guifg=#cee65c guibg=NONE]]
vim.cmd [[hi PreCondit guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Debug guifg=#cee65c guibg=NONE]]
vim.cmd [[hi SpecialChar guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Conditional guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Todo guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Special guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Label guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Delimiter guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Number guifg=#cee65c guibg=NONE]]
vim.cmd [[hi CursorLineNR guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Define guifg=#cee65c guibg=NONE]]
vim.cmd [[hi MoreMsg guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Tag guifg=#cee65c guibg=NONE]]
vim.cmd [[hi String guifg=#cee65c guibg=NONE]]
vim.cmd [[hi MatchParen guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Macro guifg=#cee65c guibg=NONE]]
vim.cmd [[hi DiffChange guifg=#cee65c guibg=NONE]]
vim.cmd [[hi GitGutterChange guifg=#cee65c guibg=NONE]]
vim.cmd [[hi cssColor guifg=#cee65c guibg=NONE]]
vim.cmd [[hi Function guifg=#61bff8 guibg=NONE]]
vim.cmd [[hi Directory guifg=#9b50ff guibg=NONE]]
vim.cmd [[hi markdownLinkText guifg=#9b50ff guibg=NONE]]
vim.cmd [[hi javaScriptBoolean guifg=#9b50ff guibg=NONE]]
vim.cmd [[hi Include guifg=#9b50ff guibg=NONE]]
vim.cmd [[hi Storage guifg=#9b50ff guibg=NONE]]
vim.cmd [[hi cssClassName guifg=#9b50ff guibg=NONE]]
vim.cmd [[hi cssClassNameDot guifg=#9b50ff guibg=NONE]]
vim.cmd [[hi Statement guifg=#46d4f6 guibg=NONE]]
vim.cmd [[hi Operator guifg=#46d4f6 guibg=NONE]]
vim.cmd [[hi cssAttr guifg=#46d4f6 guibg=NONE]]


vim.cmd [[hi Pmenu guifg=#dadada guibg=#454545]]
vim.cmd [[hi SignColumn guibg=#213531]]
vim.cmd [[hi Title guifg=#dadada]]
vim.cmd [[hi LineNr guifg=#747474 guibg=#213531]]
vim.cmd [[hi NonText guifg=#c481ff guibg=#213531]]
vim.cmd [[hi Comment guifg=#c481ff gui=italic]]
vim.cmd [[hi SpecialComment guifg=#c481ff gui=italic guibg=NONE]]
vim.cmd [[hi CursorLine guibg=#454545]]
vim.cmd [[hi TabLineFill gui=NONE guibg=#454545]]
vim.cmd [[hi TabLine guifg=#747474 guibg=#454545 gui=NONE]]
vim.cmd [[hi StatusLine gui=bold guibg=#454545 guifg=#dadada]]
vim.cmd [[hi StatusLineNC gui=NONE guibg=#213531 guifg=#dadada]]
vim.cmd [[hi Search guibg=#c481ff guifg=#dadada]]
vim.cmd [[hi VertSplit gui=NONE guifg=#454545 guibg=NONE]]
vim.cmd [[hi Visual gui=NONE guibg=#454545]]
